Thu Nov  3 00:25:40 2022 - INFO  - Start to prepare the test environment.
Failed to enable unit: Unit file pmcd.service does not exist.
Failed to start pmcd.service: Unit pmcd.service not found.
Failed to enable unit: Unit file pmlogger.service does not exist.
Failed to start pmlogger.service: Unit pmlogger.service not found.
Thu Nov  3 00:27:49 2022 - INFO  - End to prepare the test environment.
Thu Nov  3 00:27:51 2022 - INFO  - Start to run test.
oe_test_pmdate.sh:行29: pmdate：未找到命令
Thu Nov  3 00:27:55 2022 - ERROR - oe_test_pmdate.sh line 30
oe_test_pmdate.sh:行31: pmdate：未找到命令
Thu Nov  3 00:27:58 2022 - ERROR - oe_test_pmdate.sh line 32
oe_test_pmdate.sh:行33: pmdate：未找到命令
Thu Nov  3 00:28:01 2022 - ERROR - oe_test_pmdate.sh line 34
oe_test_pmdate.sh:行35: pmdate：未找到命令
Thu Nov  3 00:28:04 2022 - ERROR - oe_test_pmdate.sh line 36
oe_test_pmdate.sh:行37: pmdate：未找到命令
Thu Nov  3 00:28:07 2022 - ERROR - oe_test_pmdate.sh line 38
oe_test_pmdate.sh:行39: pmdate：未找到命令
Thu Nov  3 00:28:10 2022 - ERROR - oe_test_pmdate.sh line 40
Thu Nov  3 00:28:13 2022 - INFO  - End to run test.
Thu Nov  3 00:28:16 2022 - ERROR - failed to execute the case.
Thu Nov  3 00:28:19 2022 - INFO  - Start to restore the test environment.
Traceback (most recent call last):
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 0:14:05 ago on 2022年11月03日 星期四 00时13分08秒.\nNo match for argument: pcp\nError: Unable to find a match: pcp'
Thu Nov  3 00:28:34 2022 - INFO  - End to restore the test environment.
