Thu Nov  3 01:18:27 2022 - INFO  - Start to prepare the test environment.
Failed to enable unit: Unit file pmcd.service does not exist.
Failed to start pmcd.service: Unit pmcd.service not found.
Failed to enable unit: Unit file pmlogger.service does not exist.
Failed to start pmlogger.service: Unit pmlogger.service not found.
oe_test_pmstat.sh:行24: pcp：未找到命令
Thu Nov  3 01:20:58 2022 - INFO  - End to prepare the test environment.
Thu Nov  3 01:21:01 2022 - INFO  - Start to run test.
oe_test_pmstat.sh:行30: pmstat：未找到命令
Thu Nov  3 01:21:05 2022 - ERROR - oe_test_pmstat.sh line 31
oe_test_pmstat.sh:行32: pmstat：未找到命令
Thu Nov  3 01:21:09 2022 - ERROR - oe_test_pmstat.sh line 33
oe_test_pmstat.sh:行34: pmstat：未找到命令
Thu Nov  3 01:21:12 2022 - ERROR - oe_test_pmstat.sh line 35
oe_test_pmstat.sh:行36: pmstat：未找到命令
Thu Nov  3 01:21:16 2022 - ERROR - oe_test_pmstat.sh line 37
oe_test_pmstat.sh:行38: pmstat：未找到命令
Thu Nov  3 01:21:19 2022 - ERROR - oe_test_pmstat.sh line 39
oe_test_pmstat.sh:行40: pmstat：未找到命令
Thu Nov  3 01:21:22 2022 - ERROR - oe_test_pmstat.sh line 41
oe_test_pmstat.sh:行42: pmstat：未找到命令
Thu Nov  3 01:21:26 2022 - ERROR - oe_test_pmstat.sh line 43
oe_test_pmstat.sh:行44: pmstat：未找到命令
Thu Nov  3 01:21:30 2022 - ERROR - oe_test_pmstat.sh line 45
oe_test_pmstat.sh:行46: pmstat：未找到命令
Thu Nov  3 01:21:33 2022 - ERROR - oe_test_pmstat.sh line 47
oe_test_pmstat.sh:行48: pmstat：未找到命令
Thu Nov  3 01:21:36 2022 - ERROR - oe_test_pmstat.sh line 49
oe_test_pmstat.sh:行50: pmstat：未找到命令
Thu Nov  3 01:21:41 2022 - ERROR - oe_test_pmstat.sh line 51
Thu Nov  3 01:21:44 2022 - INFO  - End to run test.
Thu Nov  3 01:21:47 2022 - ERROR - failed to execute the case.
Thu Nov  3 01:21:50 2022 - INFO  - Start to restore the test environment.
Traceback (most recent call last):
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 173, in <module>
    exitcode = rpm_remove(args.node, args.pkgs, args.tempfile)
  File "/root/mugen/mugen-riscv/libs/locallibs/rpm_manage.py", line 144, in rpm_remove
    with open(tmpfile, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Last metadata expiration check: 0:16:45 ago on 2022年11月03日 星期四 01时03分34秒.\nNo match for argument: pcp\nError: Unable to find a match: pcp'
Thu Nov  3 01:22:07 2022 - INFO  - End to restore the test environment.
